### ISSUE TITLE
Correct Readme

### ISSUE THREAD

**Issue by NikKovIos** [west0r/SwiftyVK#68]
There are some headers, that not looks correctly. Like `##Integration ###Manually`
Also, as it is a vkontakte sdk and most of visitors are russian - it would be clever to write Readme in russian language.

**Comment by west0r** [comment]
Спасибо за замечания. Странно, что README стало выглядеть так. Возможно, у GitHub изменился формат markdown разметки. Поправим.

Сейчас я думаю по поводу русского языка. Скорее всего README, на нем будет либо опциональным (так как GitHub позволяет делать локализованные README), либо единственным. Но это планируется только в будущем.

**Comment by west0r** [comment]
markdown поправил. Доку на русском буду писать к SwiftyVK  v3 (:
