### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by ilyakooo0** [west0r/SwiftyVK#71]
'error SwiftyVKApiError[5]: User authorization failed: invalid session.'

This error isn't represented in the API as far as I am aware. 

The way I have fixed it is manually logging out and back in.

**Comment by west0r** [comment]
https://vk.com/dev/errors 
5 - Авторизация пользователя не удалась

Библиотека не должна ее отлавливать.

При каких условиях происходит ошибка?

**Comment by ilyakooo0** [comment]
При запуске приложения после долгого периода неактивности. 

Какой-то токен вроде истекает 

По логике должен вызываться vkAutorizationFailedWith делегата

**Comment by west0r** [comment]
Выше я неправильно написал.

Если стоит автоматический отлов ошибок и в запросе возвращается такая ошибка, то библиотека попытается показать диалог авторизации. `vkAutorizationFailedWith` возвращается, если ошибка произошла в ходе показа диалога авторизации.

**Comment by west0r** [comment]
Возможно истек токен и отлов ошибок в конфиге или этом запросе выключен. По деволту отлов включен.

**Comment by ilyakooo0** [comment]
The only way to change the error catching behavior is to change the catchErrors property.
I don't ever even mention it in my code.

![screen shot 2017-06-11 at 11 55 30 am](https://user-images.githubusercontent.com/6209627/27009680-f4eea12e-4e9c-11e7-9411-0120444a90ae.png)

**Comment by west0r** [comment]
Видимо, такое может случится при невалидности токена и попытки переавторизации, если вью не смогла отобразиться. Сейчас в этом месте не самый лучшей код. 
К сожалению, я не смог воспроизвести ошибку. Если есть возможность описать шаги воспроизведения ошибки в демо проекте, или приложить другой демо-проект с ее воспроизведением, то буду признателен.

**Comment by ilyakooo0** [comment]
У меня самого это случается далеко не каждый раз. 
Только после очень длительного неиспользования. Т е да, истёк токен. 

Я так понимаю, в следующей версии ты эту часть собираешься переписывать?

**Comment by west0r** [comment]
@ilyakooo0 она уже переписана)

**Comment by ilyakooo0** [comment]
Тогда закрываю до лучших времён
