### ISSUE TITLE
Получение LongPoll обновлений

### ISSUE THREAD

**Issue by PeCheRukiN** [west0r/SwiftyVK#72]
### New Issue Checklist

* [x] I have looked at the [README.md](./README.md)
* [x] I have looked at the [Example project](./Example)
* [x] I have filled out this issue template.

### Issue Info

 Info                                   | Value                               |
-------------------------|-------------------------------------|
 Platform                           |  ios
 Platform Version             | 10.3
  Swift Version                  | 3.1
 SwiftyVK Version            | 2.0
 Integration Method         | cocoapods
 
### Issue Description

Доброго времени суток! Подскажите, пожалуйста, как принимается ответ от LongPollServer? 
Я запускаю VK.LP.start() и подписываюсь на все обновления в NotificationCenter:

NotificationCenter.default.addObserver(self, selector: #selector(getVKUpdates), name: VK.LP.notifications.typeAll, object: nil)

getVKUpdates метод прикрепляю скрином. Для проверки я отправлял себе с другого аккаунта сообщения, но ответ мне всегда приходит

{
  "history" : [

  ],
  "profiles" : [

  ],
  "messages" : {
    "items" : [

    ],
    "count" : 0
  }
}
![2017-06-16 23 25 06](https://user-images.githubusercontent.com/19149219/27235436-0db56d08-52eb-11e7-8213-3a1e587fdc07.png)

**Comment by ilyakooo0** [comment]
Приходят пустые поля из-за того, что на сервере не было никаких изменений. т е не присылались никакие сообщения и т д

LongPoll - для того, чтобы можно было обрабатывать только изменения, не запрашивая все диалоги каждый раз.

**Comment by PeCheRukiN** [comment]
Да, я понял, для проверки я отправлял себе с другого аккаунта сообщения, но ответ с сервера приходил пустой.

**Comment by ilyakooo0** [comment]
В каком из `response` приходит пустой результат?

для `longPollHistory` нужен еще и аргумент `pts`

**Comment by PeCheRukiN** [comment]
В getLongPollHistory. А где можно взять pts?

**Comment by ilyakooo0** [comment]
https://vk.com/dev/messages.getLongPollHistory

оно приходит от longPoll сервера

**Comment by PeCheRukiN** [comment]
От longPollServer получаю
"key" : "b392cb2321b34d8ab34c5b18cd8a142298bd418f",
 "server" : "imv4.vk.com\/im1930",
 "ts" : 1846317907

**Comment by ilyakooo0** [comment]
Это ты получил адрес сервер и параметры, с которым надо сделать запрос.

Я не уверен, т к часть с longPoll писал не я и у меня в проекте это уже написано вручную, но по-моему в библиотеке надо просто подписаться на обновления и вызвать `VK.LP.start()`

см: конец `README.md`

**Comment by PeCheRukiN** [comment]
Все это сделал, читал и README.md и документацию Vk api, много всего перепробовал, но никак не могу решить эту задачу.

**Comment by ilyakooo0** [comment]
Секунду. Ты вообще не то делаешь. Библиотека вызывает `getVKUpdates` и хочет передать как параметр результаты, но у функции вообще нет параметров.

Если же функция должна вручную запрашивать все сервера, то зачем тебе вообще `VK.LP.start()`

На сколько я понял, функция должна принимать объект формата:
`{"ts":1820350874,"updates":[­[4,1619489,561,123456,1464958914," ... ","hello", {"attach1_type":"photo","attach1":"123456_414233177", "attach2_type":"audio","attach2":"123456_456239018"}]]}`

см: https://vk.com/dev/using_longpoll

**Comment by frooman** [comment]
Вот как у меня, живой пример

Подписался 
        NotificationCenter.default.addObserver(self, selector: #selector(self.VK_LP_notifications_typeAll(_:)), name: VK.LP.notifications.typeAll, object: nil)


Вот обрабатываю

@objc func VK_LP_notifications_typeAll(_ notification: Notification) {
            guard let objects = (notification.object as? JSONWrapper)?.unwrap else { return }
            guard
                let hashResiveLP = (notification.object as? JSONWrapper)?.hashValue,
                hashResiveLP != self.hashLP else { return }
            
            self.hashLP = hashResiveLP
            
            for object in objects {
                
                //printScope.debug("object \(object)")
                
                switch object[0].int ?? 0 {
                    
                case 4: //Сообщения
                    
                    //flag
                    let flag = object[2].int
                    
                    
                    if FlagToParametrVK(flag, parametr: 1) == 1 { //исходящее
                        if FlagToParametrVK(flag, parametr: 9) == 1 { //исходящее медиа да : нет
                            self.NewOutboxMediaMessage(object)
                            continue
                        } else {
                            self.NewOutboxMessage(object)
                            continue
                        }
                    } else { //входящее
                        if object[3].int ?? 0 == self.account_id { //назначение равен id аккаунта (сам себе)
                            if FlagToParametrVK(flag, parametr: 9) == 1 { //исходящее сам себе медиа да : нет
                                self.NewOutboxMediaMessage(object)
                                continue
                            } else {
                                self.NewOutboxMessage(object)
                                continue
                            }
                        }
                        
                        if object[3].int ?? 0 > 0 { //входящее назначение группа да : нет
                            if  abs(object[3].int ?? 0) - 2000000000 > 0 {
                                NotificationCenter.default.post(name: Notification.Name(rawValue: "vk_new_inbox_message"), object: "в группе \(object[5].string ?? "")")
                            } else {
                                VK_WallsPage_Api().ReadDataUserFirst(object[3].int ?? 0, completionHandler: { (task) in
                                    let name = "\(task?.last_name ?? "") \(task?.first_name ?? "")"
                                    NotificationCenter.default.post(name: Notification.Name(rawValue: "vk_new_inbox_message"), object: "от \(name)")
                                })
                            }
                        } else {
                            NotificationCenter.default.post(name: Notification.Name(rawValue: "vk_new_inbox_message"), object: "от Сообщества")
                        }
                        
                        if FlagToParametrVK(flag, parametr: 9) == 1 { // входящее медиа да : нет
                            self.NewInboxMediaMessage(object)
                            continue
                        } else {
                            self.NewInboxMessages(object)
                            continue
                        }
                    }
                    
                case 6: // Прочтены входящие
                    self.ReadInboxMessage(object)
                    //print(object)
                    continue
                    
                case 7: // Прочтены отправленые
                    self.ReadOutboxMessage(object)
                    //print(object)
                    continue
                    
                case 61: //набор текста в окне
                    //self.MessageInboxWrite(object)
                    continue
                    
                case 8: //друг стал онлайн
                    NotificationCenter.default.post(name: Notification.Name(rawValue: "vk_friend_online"), object: abs(object[1].int ?? 0))
                    continue
                    
                case 9: //друг стал оффлайн
                    NotificationCenter.default.post(name: Notification.Name(rawValue: "vk_friend_offline"), object: abs(object[1].int ?? 0))
                    continue
                    
                default:
                    continue
                }
            }
    }

**Comment by PeCheRukiN** [comment]
Спасибо! Все работает!
