### ISSUE TITLE
Can not authorize with OSStatus error -10814

### ISSUE THREAD

**Issue by simorakkaus** [west0r/SwiftyVK#73]
Hi!
I'm trying to take advantage of using SwiftyVK lib for my project but stuck right in authorization.
I had step by step implementation for adding the library from here [https://github.com/west0r/SwiftyVK#authorization-with-vk-app](url)

but when I've tried to launch authorization method 
`VK.logIn()`

I've got the error
VKIntegrationTest[1109:598558] -canOpenURL: failed for URL: "vk[my app id]://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

OSSStatus says that 10814 is

>No application in the Launch Services database matches the input criteria.

I'm sure I have official VK app on my device and more than that 10814 is a Mac error, but I'm into iPhone.

**Comment by simorakkaus** [comment]
Sorry for disturbing, it was my bad, the lib works as expected, but I wish description of installation process and library usage clearer, if you need help with that I'm happy to help.

**Comment by PutkovDimi** [comment]
Hi @simorakkaus @west0r !
I have the same error 
`"The operation couldn’t be completed. (OSStatus error -10814.)"`

This mistake appears every time I try to authorize. If I make it as in example with 

`        if let rootController = UIApplication.shared.keyWindow?.rootViewController{
            rootController.present(viewController, animated: true)
        }
`

it works nice, but I don't want to do my login controller is root. So when I try this code

`
let main = UIStoryboard(name: "Main", bundle: nil)
        let vc = main.instantiateViewController(withIdentifier: "LoginViewController")
        vc.present(viewController, animated: true)
`

 I have an error as I described above.

Hope you can help me!

**Comment by PutkovDimi** [comment]
So I fixed the problem just using both parts of the code :) 
Maybe it will be useful for somebody 
`
let main = UIStoryboard(name: "Main", bundle: nil)
        let vc = main.instantiateViewController(withIdentifier: "LoginViewController") as UIViewController
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.window?.rootViewController = vc
        if let rootController = UIApplication.shared.keyWindow?.rootViewController{
            rootController.present(viewController, animated: true)
        }
`

**Comment by west0r** [comment]
@PutkovDimi , do you fix `OSStatus error -10814` or not?

**Comment by djdance** [comment]
Тоже наткнулся на OSStatus error -10814. По всей видимости, как только поменял стартовый навигатор. Что делать-то?

**Comment by djdance** [comment]
Ага, я понял. Если стартовый контроллер 0 заменяется контроллером 1, то либа вылетает: она пытается подцепиться к контроллеру 0, которого уже нет:

-canOpenURL: failed for URL: "vkauthorize://authorize?client_id=******&scope=******&display=mobile&v5.92&sdk_version=1.3.17&response_type=token&revoke=1" - error: "Не удалось завершить операцию. (OSStatus, ошибка -10814)"

Warning: Attempt to present <SwiftyVK.WebControllerIOS: 0x4d97d90> on <theApp.controller0: 0x14e72d20> whose view is not in the window hierarchy!
`

решение простое, как и написано: замените в SwiftyVKDelegate контроллер в функции vkNeedToPresent. Было: 

`if let rootController = UIApplication.shared.keyWindow?.rootViewController {
            rootController.present(viewController, animated: true)
        }`

а надо

`if let topVC = UIApplication.getTopMostViewController() {
            topVC.present(viewController, animated: true)
        }`

всякие варианты getTopMostViewController() гуглятся например тут https://stackoverflow.com/a/50656239/2233069
