### ISSUE TITLE
Отправка/прием видео в личных сообщениях.

### ISSUE THREAD

**Issue by PeCheRukiN** [west0r/SwiftyVK#74]
### New Issue Checklist

* [x] I have looked at the [README.md](./README.md)
* [x] I have looked at the [Example project](./Example)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |ios
 Platform Version        | 10.3
  Swift Version          | 3.1
 SwiftyVK Version        | 2.0.0
 Integration Method      | cocoapods
 
### Issue Description

Здравствуйте! Пытаюсь отправить видео в личном сообщении, но в диалогах вместо видео отображается "...".
![2017-06-19 13 52 49](https://user-images.githubusercontent.com/19149219/27272944-09885a5c-54f7-11e7-9186-6a6cada0256e.png)

А при загрузке диалога методом getHistory получаю в ответ от сервера:
![2017-06-19 14 03 18](https://user-images.githubusercontent.com/19149219/27273214-3862b772-54f8-11e7-8659-5dd7b4d2c5b4.png)
Тут нет поля с url видео для воспроизведения.
Подскажите, пожалуйста, что я делаю не так?

**Comment by ilyakooo0** [comment]
Ты все делаешь правильно. Видео для воспроизведения надо получать из другого метода с помощью `owner_id`, `id` и `access_key`.

**Comment by PeCheRukiN** [comment]
@ilyakooo0, спасибо, теперь могу получать видео в сообщениях. А отправка видео в личном сообщении как правильно осуществляется?

**Comment by ilyakooo0** [comment]
Видео надо передать с сообщением в поле `attachment` в формате:
`<type> <owner_id>_<media_id>_<access_key>`
например:
`video85635407_165186811_69dff3de4372ae9b6e`

см: https://vk.com/dev/messages.send

**Comment by PeCheRukiN** [comment]
@ilyakooo0 я тут так и делаю https://user-images.githubusercontent.com/19149219/27272944-09885a5c-54f7-11e7-9186-6a6cada0256e.png

**Comment by west0r** [comment]
@PeCheRukiN `access_key` не вижу, чтоб передавался

**Comment by PeCheRukiN** [comment]
Вариант с access_key тоже пробовал - результат тот же, вместо видеозаписи приходит "…"

**Comment by PeCheRukiN** [comment]
Я неверно извлекал данные из response, спасибо за уделенное время!

**Comment by PeCheRukiN** [comment]
Еще один вопрос, метод VK.API.Upload.Video.fromURL сам грузит видео на сервер или нужно выгружать его самому?

**Comment by west0r** [comment]
@PeCheRukiN он не грузит видео с урла. Работает как [video.save](https://vk.com/dev/video.save). Передаешь урл на ютуб или другой сервис, с которого вк может встроить видео.
