### ISSUE TITLE
Проблема с LongPoll

### ISSUE THREAD

**Issue by PeCheRukiN** [west0r/SwiftyVK#77]
* [x] I have looked at the [README.md](./README.md)
* [x] I have looked at the [Example project](./Example)
* [x] I have filled out this issue template.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.3
  Swift Version          |  3.0.2
 SwiftyVK Version        | 2.0.8
 Integration Method      |cocoapods
 
Добрый день! У меня повторяется та же ситуация, что описана в #49 . То есть, все запросы идут строго друг за другом и при использованиии LongPoll все приложение висит в ожидании ответа от сервера.

**Comment by Amekill** [comment]
+1
Заметил такую проблему, если включен ЛП и приложение свернуто больше 5-10 секунд. При разворачивании начинают висеть все запросы. Лечил костылями - отключение ЛП при сворачивании/разворачивании и повторной активацией..

**Comment by west0r** [comment]
Спасибо за фидбек. Займусь этим в ближайшее время.

**Comment by west0r** [comment]
@PeCheRukiN готово
