### ISSUE TITLE
Удаление пода

### ISSUE THREAD

**Issue by Yurlagin** [west0r/SwiftyVK#80]
Здравствуйте! 

Удалил соответствующую строчку из Podfile, выполнил pod install, чтобы удалить под из воркспэйса и получил 82 ворнинга о нехватке такихто файлов в проекте. Все они из пода SwiftyVK. Как бы исправить этот момент, не подскажите?
![2017-08-08 18 02 15](https://user-images.githubusercontent.com/24584890/29069125-c6cbc75a-7c63-11e7-97df-8c88d78d07ca.png)

**Comment by west0r** [comment]
Скорее всего вы держали поды под индексом гита, а когда удалили библиотеку из проекта, то из файловой системы файлы удалились, а из гита нет.

 Можете сделать в корне репозитория `git add .` и потом закоммитить изменения. Ошибка должна исчезнуть.

**Comment by Yurlagin** [comment]
большое спасибо, совет помог!
