### ISSUE TITLE
Time limit for the outer request includes inner requests execution time

### ISSUE THREAD

**Issue by usr-sse2** [west0r/SwiftyVK#83]
### New Issue Checklist

* [V] I have looked at the [README.md](./README.md)
* [V] I have looked at the [Example project](./Example)
* [V] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | osx
 Platform Version        | 10.13
  Swift Version          | 3.0.1
 SwiftyVK Version        | 2.0.0
 Integration Method      | manually
 
### Issue Description

Рассмотрим загрузку фотографии в альбом. Заданы следующие параметры: таймаут для обычных запросов – 30 секунд, таймаут для загрузки файлов – 1/10 от длины файла вместо 1/1000 по умолчанию, скорость – 200 кбит/с (задана в Network Link Conditioner). Размер файла 990 КБайт,  т. е. таймаут для загрузки получается около 99000 секунд. Тем не менее, при загрузке файла через 30 секунд после начала вызывается callback onError, то есть в лимит времени для запроса getUploadServer включается время выполнения вложенного POST-запроса. Это делает невозможной загрузку файлов произвольного размера.

**Comment by west0r** [comment]
Fixed. @usr-sse2 thanx!
