### ISSUE TITLE
LongPool

### ISSUE THREAD

**Issue by Amekill** [west0r/SwiftyVK#84]
### New Issue Checklist

* [+] I have looked at the [README.md](./README.md)
* [+] I have looked at the [Example project](./Example)
* [+] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.0 b10
  Swift Version          | 4.0
 SwiftyVK Version        | 2.0.12
 Integration Method      | carthage
 
### Issue Description

LongPool ложит приложение когда отключается/слабый интернет. Простой пример как воспроизвести: 
1. Включить его
2. Свернуть приложение и отключить интернет
3. Развернуть
Приложение зависнет полностью до того момента, пока longpoll не гетнет сервер. Так-же иногда проскакивает краш приложения с ошибкой на swiftyvk, т.к. у меня при разворачивании выполняется VK.API.remote и лонг с методами как-то конфликтует

**Comment by west0r** [comment]
Воспроизводится ли это в демо проекте библиотеки?
Может в каком-то запросе вы блокируете главный поток? SwiftyVK посылает все запросы в своем приватном  потоке и блочить UI не должен.
Пожалуйста, приложите креш-логи и любую дополнительную информацию.

**Comment by west0r** [comment]
Я сделал правки в отдельной ветке. Это должно убрать краш.
С зависанием вопрос остается открытым. Я пока не воспроизвел. Нужно больше информации.

**Comment by Amekill** [comment]
Да, такое наблюдается и на демо проекте для iOS. Я авторизировался и дописал в конце метода usersGet() запуск лонга. При отключении интернета и сворачивании/открытии контрол центра приложение зависает целиком, если приходит уведомление с другого - оно вылезает с хорошим подвисанием

**Comment by west0r** [comment]
Извеняюсь, но я не совсем понял флоу из последнего сообщения. Особенно про уведомление.

**Comment by Amekill** [comment]
Я взял текущий демо проект из главное ветки SwiftyVK, авторизовался в нем через вк, дописал в классе APIWorker в методе usersGet() запуск лонга VK.LP.start(), при нажатии на users.get в собранном проекте выполняется запрос и запуск лонга. Далее если свернуть/открыть контрол центр и отключить интернет, то приложение зависает намертво, а системные уведомления если приходят когда оно (зависшее приложение) на экране, то они вываливаются сверху с очень большим подвисанием анимации. iOS 11 dev beta 10, iPhone 6s

**Comment by Amekill** [comment]
По поводу крашей: ошибка осталась, но теперь она сразу после сворачивания
![2017-09-09 17 26 05](https://user-images.githubusercontent.com/27199647/30241017-21c12fe0-9584-11e7-9f6d-32873ab2514e.png)

**Comment by frooman** [comment]
Добрый день
У меня примерно тоже самое, но на сколько я понял при свернутой программе и
запущеном longpool приложение продолжает делать запросы каждые 30 секунд.
Но у меня по каким-то причинам запросы просто копятся в очереди без
выполнения. При разворачивания из бекграунда они начинают выполняться, все
накопленные запросы, тут и появляется зависание. В api для Swift 2 запросы
в бекграунде полность выполнялись.

сб, 9 сент. 2017 г. в 17:17, Леша <notifications@github.com>:

**Comment by west0r** [comment]
Обновил #85.  @Amekill @frooman проверяйте ваши кейсы. Если все ок, замержу в мастер.

Нормальное поведение LongPoll при сворачивании приложения или отключении интернета - сбрасывать все запросы и уходить в режим ожидания пока приложение не окажется в foreground c интернетом.

**Comment by Amekill** [comment]
@west0r Вроде бы исчезли краши и даже зависания, спасибо )

**Comment by west0r** [comment]
@Amekill спасибо Вам за наводку. Issue я пока открою. Он закроется сам при мердже фикса.
